audio:
  Azure:
    service_region: SERVICE_REGION
    speech_key: SPEECH_KEY
  provider: Azure

captioning:
  provider: Azure

llm:
  DeepSeek:
    api_key: YOUR_API_KEY
    base_url: null
    model_name: null
  Gemini:
    api_key: YOUR_API_KEY
    base_url: null
    model_name: null
  Moonshot:
    api_key: YOUR_API_KEY
    base_url: null
    model_name: null
  Ollama:
    api_key: YOUR_API_KEY
    base_url: null
    model_name: null
  OpenAI:
    api_key: YOUR_API_KEY
    base_url: http://base.url.openai
    model_name: null
  Azure:
    api_key: YOUR_API_KEY
    base_url: http://base.url.openai
    model_name: null
  Qianfan:
    api_key: YOUR_API_KEY
    base_url: null
    model_name: null
  provider: OpenAI
resource:
  pexels:
    api_key: API_KEY
  pixabay:
    api_key: 456
  provider: pexels
ui:
  language: zh-CN
video:

test_mode: False

