audio:
  Azure:
    service_region: SERVICE_REGION
    speech_key: SPEECH_KEY
  provider: Azure

captioning:
  provider: Azure

llm:
  DeepSeek:
    api_key: YOUR_API_KEY
    base_url: null
    model_name: null
  Baichuan:
    api_key: YOUR_API_KEY
    model_name: Baichuan3-Turbo
  Moonshot:
    api_key: YOUR_API_KEY
    model_name: moonshot-v1-8k
  Ollama:
    api_key: YOUR_API_KEY
    base_url: null
    model_name: null
  OpenAI:
    api_key: YOUR_API_KEY
    model_name: gpt-3.5-turbo
  Azure:
    api_key: YOUR_API_KEY
    base_url: http://base.url.openai
    model_name: null
  Qianfan:
    api_key: YOUR_API_KEY
    secret_key: YOUR_SK_KEY
    model_name: ERNIE-Bot-turbo
  provider: Moonshot
resource:
  pexels:
    api_key: API_KEY
  pixabay:
    api_key: API_KEY
  provider: pexels
ui:
  language: zh-CN
video:

test_mode: False

